CC=g++

Target: Domain_separation_improper.cpp Least_Privelage_Improper.cpp Process_Isolation_Improper.cpp Resource_Encapsulation_Improper.cpp ModularityWrong.cpp
	$(CC) -o domain Domain_separation_improper.cpp
	$(CC) -o least Least_Privelage_Improper.cpp
	$(CC) -o proccess Process_Isolation_Improper.cpp
	$(CC) -o resource Resource_Encapsulation_Improper.cpp
	$(CC) -o modularity ModularityWrong.cpp

obj: Domain_separation_improper.o Least_Prevelage_Improper.o Process_Isolation_Improper.o Resource_Encapsulation_Improper.o ModularityWrong.o
