CC=g++

Target: Abstraction_Improper.cpp Data_Hiding_Improper.cpp Minimization_Improper.cpp Simplicity_Improper.cpp
	$(CC) -o abstractI Abstraction_Improper.cpp
	$(CC) -o dataI Data_Hiding_Improper.cpp
	$(CC) -o minI Minimization_Improper.cpp
	$(CC) -o simpleI Simplicity_Improper.cpp

obj: Abstraction_Improper.o Data_Hiding_Improper.o Minimization_Impropero Simplicity_Improper.o
