CC=g++

Target: Domain_separation.cpp Least_Privelage.cpp Proccess_Isolation.cpp Resource_Encapsulation.cpp
	$(CC) -o domain Domain_separation.cpp
	$(CC) -o least Least_Privelage.cpp
	$(CC) -o proccess Proccess_Isolation.cpp
	$(CC) -o resource Resource_Encapsulation.cpp

obj: Domain_separation.o Least_Prevelage.o Proccess_Isolation.o Resource_Encapsulation.o
