CC=g++

Target: Abstraction.cpp Data_Hiding.cpp Minimization.cpp Simplicity.cpp
	$(CC) -o abstract Abstraction.cpp
	$(CC) -o data Data_Hiding.cpp
	$(CC) -o min Minimization.cpp
	$(CC) -o simple Simplicity.cpp

obj: Abstraction.o Data_Hiding.o Minimization.o Simplicity.o
